### ISSUE TITLE
Vytvořit UI - komponenty pro search bar

### ISSUE THREAD

**Issue by adamtretera** [FenixBois/optimistic-rabbit-web#6]
Vytvořit komponenty:
SearchBarForm která bude obsahovat 

SeachBar plus ty tlačítka viz figma create a search

Mužeš zkusit naistalovat knihovnu react-hook-form a hrát s i s tím formulářem. (zda to půjde)

viz.
https://www.figma.com/proto/TwRY7Npbp66QibmRuAhP1q?node-id=1505%3A435590

**Comment by PeanutButte7** [comment]
- adde form item
